# Hi there!
# These are the settings for Selfstarter.
# This is more tidy than changing the HTML if all you want to do is rename things and swap out images

# You should totally change the HTML and CSS though
# Checkout app/assets/stylesheets/variables.css.scss to change around the CSS quickly

# Set your project goal here - if you manually want to adjust your progress to test the site, head over to the Order model (app/models/order.rb)
project_goal: 100
# If you want to edit the FAQ, head over to app/views/preorder/homepage/_faqs.html.erb


# How many people do you need to back with how much?
project_total: <%= 100 * 19.95 %>
# 100 is the number of backers backing with 19.95 each. Configure at your will.


# This'll be both the page title (<title></title>) and the name in the header
product_name: "Selfstarter"

# An image showcasing your product -- it'll show up when you pin your product
# It should be in app/assets/images
product_image_path: "my-product-image.png"


# YouTube or Vimeo Video URL (The embed URL, without the query string options)
video_embed_url: "http://www.youtube.com/embed/iO5tm0JropI"

# Amazon settings -- you'll need an Amazon Payments account, sign up here --> http://bit.ly/SGksTv
# To find your access key and secret key, head over to here --> http://bit.ly/R4I4ky (Follow that guide in the Seller Central page)
amazon_access_key: "YOUR_AMAZON_ACCESS_KEY"
amazon_secret_key: "YOUR_AMAZON_SECRET_KEY"
price: 	19.95

# Moip settings -- you'll need a moip account, signup here -->


payment_description: "You really should change this text because people will see it on Amazon's order page!!!!!"

# Amazon limits how much we can charge people with their Multi-Use tokens.
# You probably should add some leeway to account for international shipping
charge_limit: 25.00


# When the project should end
expiration_date: <%= DateTime.now + 45 %>

# On Lockitron, it's "First Batch Ships in March 2013"
ships: "O projeto será realizado se financiado até <%= I18n.l(DateTime.now+45, format: :as_date) %>"


# On Lockitron, this is "Only $149 for a limited time"
price_human: "Apoie com R$ 10 agora!"

# Social Stuff
facebook_app_id: "1234567890"

# Tweets are prefixed with "I'm #{Settings.primary_stat} number X for #{Settings.product_name}"
# Maybe mention something about your product vision -- e.g. "to replace keys with my phone"
tweet_text: "to crowdfund"

# Google Analytics
google_id: "1234567890"

# If you want to change the images for the key points (e.g. "Kickstarter is not a store")
# They're in app/assets/images/#{pointer_number}-background.png
# So, the first key point, it's at app/assets/images/1-background.png
# Alternatively, change it up in app/assets/stylesheets/homepage/key_points.css.scss
